theme: jekyll-theme-slate
title: "Information Assurance and Security Labs" # Leave title empty to hide repo name
description: "This repository contains lab exercises for BCIT's ACIT 4630 Information Assurance and Security 
course. The labs provide a practical foundation in information security, covering a range of 
essential topics and tools to help secure systems on a LAN. Students will explore 
vulnerability scanning, cryptography, incident response, and various network attack 
simulations." # Leave description empty to hide description
